### ISSUE TITLE
Feature Request: Escape regex meta characters in input

### ISSUE THREAD

**Issue by Ajaymamtora** [chrisgrieser/nvim-rip-substitute#18]
### Checklist

- [X] I have read the README.
- [X] The feature would be useful to more users than just me.

### Feature Requested

Sometimes it's useful to search for some literal text that you would like to extend with regex.

You could paste in the literal text, escape regex, then modify the regex to extend what it searches for.

e.g. search 'app.component.' -> escape regex which leaves 'app\.component\.' in the input box, then you can extend it, e.g. 'app\.component\.(ts|html)'.

This is also part of my fork which is mangled at the minute

**Comment by chrisgrieser** [comment]
I am sorry, but I am not able to follow what exactly you are requesting. Could you describe it more clearly?

**Comment by chrisgrieser** [comment]
> You could search for "app.component.", invoke and the search input becomes "app\.component\.".
>
> Then you can type "(html|ts)" at the end so the full search becomes "app\.component\.(html|ts)".

Ah, now I understand. Actually, that you can already achieve. If you have set `prefill.visual = "selectionFirstLine"` (the default), then in your log file, you can go to `app.component.` and select it. Calling rip-substitute via lua function will then prefill the visual selection automatically for you. (This is not possible if using `:RipSubstitute`, since vim switched to normal when using `:`.)

**Comment by chrisgrieser** [comment]
> does it escape regex meta chars for you?
yes, it already does that. Since the very beginning of this plugin.

The only two reasons why it would not are:
1. you changed the setting for `prefill.visual`, or
2. you are calling the excommand (`:RipSubstitute`), which does not support prefilling.
