### ISSUE TITLE
Feature Request: Add different search engines

### ISSUE THREAD

**Issue by sbushmanov** [chrisgrieser/nvim-rip-substitute#25]
### Checklist

- [X] I have read the README.
- [X] The feature would be useful to more users than just me.

### Feature Requested

I think the decision to take `ripgrep` as a search engine is just great "to get the job done" (after spending about an hour trying to find substitution pattern with the native vim tooling  and giving up I did the necessary substitution with `nvim-rip-substitute` in a matter of seconds).

However, `ripgrep`'s dialect is special and different to say POSIX basic or extended.

I believe this plugin could make a great educational resource to study `grep` (due to its highlighting preview) if couple of grep engines -- like POSIX `grep` or `egrep` -- are added, with clear indication in the popup what regex flavour is used.

**Comment by chrisgrieser** [comment]
> I think the decision to take ripgrep as a search engine is just great "to get the job done" (after spending about an hour trying to find substitution pattern with the native vim tooling and giving up I did the necessary substitution with nvim-rip-substitute in a matter of seconds).

thanks! that was also my experience, which is why I created this plugin :)

> I believe this plugin could make a great educational resource to study grep (due to its highlighting preview) if couple of grep engines -- like POSIX grep or egrep -- are added, with clear indication in the popup what regex flavour is used.

For the case you describe, I think it would be better to simply compare the output of `ripgrep` and `grep` in the terminal – I do not think that the "educational value" of comparing syntaxes justifies increasing the complexity of the plugin. 

Also, the plugin would not even be able to work with `grep`, since it does not have a `--replace` flag like `ripgrep`.
